package: transient
version: '0.0.1-dev'
author: 'eaCe'

requires:
  redaxo: ^5.12.0
  php:
    version: '>=7.4'

installer_ignore:
  - node_modules
  - .git
  - .gitignore
  - .github
  - package.json
  - yarn.lock
  - resources
  - .editorconfig
  - .eslintrc.js
  - .stylelintrc.js
  - phpcs.xml
