name: PHP checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  check:

    runs-on: ubuntu-latest
    permissions:
      contents: write  # for Git to git apply

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: gd, intl, pdo_mysql
          coverage: none # disable xdebug, pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

#      - name: Cache Composer packages
#        id: composer-cache
#        uses: actions/cache@v2
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
#          restore-keys: |
#            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

#      - name: Try to log config...
#        run: less vendor/redaxo/source/redaxo/src/core/default.config.yml

      - name: Stop Database
        if: ${{ env.ACT }}
        run: sudo service stop mysql

      - name: Setup Database Config
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_bin'
          mysql version: '8.0'
          mysql database: 'redaxo5'
          mysql root password: 'root'
          mysql user: 'root'
          mysql password: 'root'

#      - name: Setup MySQL
#        run: mysql -h 127.0.0.1 --port 3306 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS redaxo5;'

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --port 3306 --password=root --silent; do
            sleep 1
          done

      - name: Setup REDAXO
        run: |
          git apply .github/workflows/default.config.yml.github-action.diff
          php .tools/bin/setup

      # copy Addon files, ignore some directories...
      # install phpmailer
      # install the addon
      # if the addon name does not match the repository name, ${{ github.event.repository.name }} must be replaced with the addon name
      - name: Copy to Addons
        run: |
          rsync -av --exclude='vendor' --exclude='.github' --exclude='.git' './' './vendor/redaxo/source/redaxo/src/addons/${{ github.event.repository.name }}'
          vendor/redaxo/source/redaxo/bin/console package:install '${{ github.event.repository.name }}'

      - name: Install test dependencies
        working-directory: vendor/redaxo/source/redaxo/src/addons/${{ github.event.repository.name }}
        run: composer install --prefer-dist --no-progress

      - name: Run lint
        working-directory: vendor/redaxo/source/redaxo/src/addons/${{ github.event.repository.name }}
        run: composer lint

      - name: Run phpcs
        working-directory: vendor/redaxo/source/redaxo/src/addons/${{ github.event.repository.name }}
        run: composer phpcs

      - name: Test...
        run: |
          vendor/redaxo/source/redaxo/bin/console system:report

      - name: Run phpunit
        working-directory: vendor/redaxo/source/redaxo/src/addons/${{ github.event.repository.name }}
        env:
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_DATABASE: redaxo5
          DB_PORT: 3306
          DB_PASSWORD: root
          DB_USERNAME: root
        run: composer test
